// nodemailer configuration!
// fake data generated by ethereal
module.exports = {
  host: "smtp.ethereal.email",
  port: 587,
  auth: {
    user: "bessie.wolf26@ethereal.email",
    pass: "2qQHT9VMrmYRqhSMRe",
  },
};
