// nodemailer configuration!
// fake data generated by ethereal
module.exports = {
  host: "smtp.ethereal.email",
  port: 587,
  auth: {
    user: "rickey28@ethereal.email",
    pass: "UKGM9cdxC4RqtBBcSq",
  },
};
